version: '2'
services:
    ramaadminapi-app:
        image: ramaadminapi
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ramaadminapi-postgresql:5432/ramaadminapi
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8443:8443
    ramaadminapi-postgresql:
        extends:
            file: postgresql.yml
            service: ramaadminapi-postgresql
